file "$(ALLMOTION)/db/allmotion_motor.db" {
pattern
 {   Sys,        Dev, Ax,      DESC, DTYP,      DIR, VELO, VBAS, ACCL, BDST, BVEL, BACC, PORT, ADDR, MRES,  PREC, EGU, DHLM,  DLLM,   INIT}
 {XF:03IDC-ES, Ez4:1,  1, "motor 1", asynMotor, 0,     5,     5,    1,    0,    0,    0,    ALM1, 0,    0.001, 3,    um,  10000, -10000, 0}
 {XF:03IDC-ES, Ez4:1,  2, "motor 2", asynMotor, 0,     5,     5,    1,    0,    0,    0,    ALM1, 1,    0.001, 3,    um,  10000, -10000, 0}
 {XF:03IDC-ES, Ez4:1,  3, "motor 3", asynMotor, 0,     5,     5,    1,    0,    0,    0,    ALM1, 2,    0.001, 3,    um,  10000, -10000, 0}
 {XF:03IDC-ES, Ez4:1,  4, "motor 4", asynMotor, 0,     5,     5,    1,    0,    0,    0,    ALM1, 3,    0.001, 3,    um,  10000, -10000, 0}
}
